### ISSUE TITLE
多次实例化构造函数时，歌词的中间变量会变成最后一个，导致无法实现双语歌词

### ISSUE THREAD

**Issue by BugKun** [frank-deng/js-lyrics#1]
模拟触发Bug：
var firstLine = new Lyrics(`[00:04.050] firstLine `);
var secondLine = new Lyrics(`[00:04.050] secondLine `);
firstLine.getLyrics()；//secondLine
secondLine.getLyrics()；//secondLine
原因：构造函数的书写方式有问题。
解决方法：我已Fork并上传修改后的源码。

**Comment by frank-deng** [comment]
代码更新了

**Comment by BugKun** [comment]
好的，谢谢了
