### ISSUE TITLE
How to open .lrc file 

### ISSUE THREAD

**Issue by sjuliper7** [frank-deng/js-lyrics#3]
i have project name is **test** and inside project i have file .lrc but when i'm use **var lrc =  new Lyrics('/test/file.lrc')** in file index.html result from instant is 
Lyrics {timestamp_offset: 0, lyrics_all: undefined, meta_info: undefined, ID_TAGS: Array(9)}
ID_TAGS: (9) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
lyrics_all: undefined
meta_info: undefined
timestamp_offset: 0
__proto__: Object

how to solve this?
i think my path file lrc is right

**Comment by frank-deng** [comment]
I'll check it later.

**Comment by frank-deng** [comment]
You must pass the full content of the .lrc file instead of the file path to `new Lyrics()`.
The full content of the .lrc file can be fetched via `XMLHttpRequest` at browser side.

**Comment by sjuliper7** [comment]
`var xhttp = new XMLHttpRequest();
            xhttp.open("GET", "haleluya.lrc", true);
            xhttp.send();
            console.log(xhttp)
            var lrc =  new Lyrics(xhttp.)
            console.log(lrc)`
i have try with XMLHttpRequest but the result still same
```
Lyrics {timestamp_offset: 0, lyrics_all: undefined, meta_info: undefined, ID_TAGS: Array(9)}
ID_TAGS: (9) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
lyrics_all: undefined
meta_info: undefined
timestamp_offset: 0
__proto__: Object
```

**Comment by sjuliper7** [comment]
Hello Mr Frank Deng, i'm student
can you help me what the meaning of this?
i
dont know the flow, i mean i dont know lyric_selected, lyrics_container and
this lyric_selected.setAttribute('selected', 'selected');
from your code.


var lrc = new Lyrics(LRC_text);
document.getElementById('audio_player').addEventListener('timeupdate',
function(){
	//Unhighlight all the lyrics
	var lyric_selected = lyrics_container.querySelectorAll('[selected]');
	for (var i = 0; i < lyric_selected.length; i++) {
		lyric_selected[i].removeAttribute('selected');
	}

	//Get the lyric to highlight
	var lyric_selected = lrc.select(this.currentTime);

	//Highlight the lyric
	if (lyric_selected != undefined && lyric_selected >= 0) {
		lyric_selected.setAttribute('selected', 'selected');
	}
});

Thank you
